### ISSUE TITLE
Endswith being produced when using escape chac

### ISSUE THREAD

**Issue by rfackroyd** [AttackIQ/pySigma-backend-microsoft365defender#1]
Hey! Thanks for making this backend, really awesome to see it here

I have noticed that when using a `contains` statement in my Sigma rules using wildcard `*` notation to denote `contains` that it is producing an `endswith` in the KQL output. This happens when I am using wildcards right after an escape `\` character.

I'll clarify through a heavily simplified example to demonstrate the issue:

Say I would like to detect a command line that has `\AppData\` in it. Therefore I create a rule and convert it like so:

```
from sigma.rule import SigmaRule
from sigma.backends.microsoft365defender import Microsoft365DefenderBackend
from sigma.pipelines.microsoft365defender import microsoft_365_defender_pipeline

sigma_rule = SigmaRule.from_yaml("""
  title: Endswith issue
  status: test
  logsource:
      category: process_creation
      product: windows
  detection:
      selection:
          CommandLine: 
            - '*\AppData\*'
      condition: selection
""")

m365def_backend = Microsoft365DefenderBackend()
pipeline = microsoft_365_defender_pipeline()
pipeline.apply(sigma_rule)
print(sigma_rule.title + " KQL Query: \n")
print(m365def_backend.convert_rule(sigma_rule)[0])
```

The output is the following:

```
Endswith issue KQL Query: 

DeviceProcessEvents
| where ProcessCommandLine endswith "\\AppData\*"
```

I was intending for the conversion to produce this instead:

```

DeviceProcessEvents
| where ProcessCommandLine contains "\\AppData\\"
```

I expect the trailing escape is causing some issues here, as without the backslash characters around `AppData`, this does not occur. The issue is that having the backslash characters around a directory name really helps to reduce false positives, so it would be great to be able to do this.

**Comment by slincoln-aiq** [comment]
Hey there,

Thanks for reporting this! However, I believe the issue is not with the backend conversion, rather the Sigma rule string that you provided.  Taking a look at the Sigma specification found here regarding escaping: https://github.com/SigmaHQ/sigma-specification/blob/main/Sigma_specification.md#escaping, the relevant bullet point that would apply to this situation is as follows:

> - The backslash before a wildcard has to be escaped to handle the value as a backslash followed by a wildcard: \\\\*

To confirm this, I created the following test in `test_backend_microsoft365defender.py` from the example you gave, but escaped the slash before the wildcard based on the documentation referenced above:

```python3
def test_microsoft365defender_escape_contains(microsoft365defender_backend: Microsoft365DefenderBackend):
    assert microsoft365defender_backend.convert(
        SigmaCollection.from_yaml(r"""
            title: Endswith issue
            status: test
            logsource:
                category: process_creation
                product: windows
            detection:
                selection:
                    CommandLine: 
                        - '*\AppData\\*'
                condition: selection
        """)
    ) == ['DeviceProcessEvents\n| where ProcessCommandLine contains "\\\\AppData\\\\"']
```

Note that I'm using a raw string for the Sigma Rule portion so the backslashes in the rule do not have to be escaped in Python, and appear as they would in the Sigma rule YAML file.  However, the expected return string is not formatted as a raw string, so I'm escaping as you would with a regular Python string.  

After running the test, it passes. Printing the output yields the following:
> DeviceProcessEvents
> | where ProcessCommandLine contains "\\\\AppData\\\\"

which yields a valid query with results (at least in the instance I'm testing it in) when copy+pasted into a M365 Advanced Hunting Query.

Could you test some of your rules again using the slash/wildcard escaping mentioned above and see if the results are as expected? If not let me know so I can look into it further, otherwise I will close this issue if everything comes back OK.

Thanks!

**Comment by rfackroyd** [comment]
Hey - so you're correct, this is the right way to do it and therefore we should stick to the specification. 

I had been storing my sigma without the double-escape and using `sigmatools` python package `mdatp.py` backend - it somehow doesn't produce the same outcome, perhaps due to the way it package handles escape characters.

This meant that the deviation from sigma spec was something that went un-noticed. Thanks for the test!
